import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Professional templates based on authority
const TEMPLATES = {
  Police: {
    headerColor: [0, 51, 102], // Dark Blue
    title: "POLICE DEPARTMENT COMPLAINT REPORT",
    logoUrl: "https://via.placeholder.com/50x50/003366/FFFFFF?text=Police" // Placeholder logo
  },
  "Utilities Department": {
    headerColor: [34, 139, 34], // Green
    title: "UTILITIES DEPARTMENT COMPLAINT REPORT",
    logoUrl: "https://via.placeholder.com/50x50/228B22/FFFFFF?text=Utility"
  },
  Court: {
    headerColor: [139, 69, 19], // Brown
    title: "COURT COMPLAINT FILING REPORT",
    logoUrl: "https://via.placeholder.com/50x50/8B4513/FFFFFF?text=Court"
  },
  default: {
    headerColor: [0, 64, 128], // Navy
    title: "OFFICIAL COMPLAINT REPORT",
    logoUrl: "https://via.placeholder.com/50x50/004080/FFFFFF?text=Lawledge"
  }
};

export async function generateComplaintPDF(complaint, authority, lawSection) {
  const doc = new jsPDF();

  // Get template
  const template = TEMPLATES[authority] || TEMPLATES.default;

  // --- 1. Professional Header with Logo ---
  doc.setFillColor(...template.headerColor);
  doc.rect(0, 0, 210, 50, 'F');

  // Add logo (placeholder - replace with actual logo URL)
  try {
    // Note: In production, load image asynchronously
    // For now, using placeholder
    doc.addImage(template.logoUrl, 'JPEG', 10, 10, 30, 30);
  } catch (e) {
    // Fallback if image fails
  }

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(template.title, 105, 25, { align: "center" });

  doc.setFontSize(12);
  doc.text("Lawledge Portal - Official Grievance Redressal", 105, 35, { align: "center" });

  // --- 2. Metadata Section ---
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  doc.text(`Tracking ID: ${complaint.tracking_code}`, 20, 60);
  doc.text(`Date Filed: ${new Date(complaint.created_at || Date.now()).toLocaleDateString()}`, 150, 60);
  doc.text(`Authority: ${authority || "General"}`, 20, 70);
  doc.text(`Law Section: ${lawSection || "N/A"}`, 150, 70);

  // --- 3. Complainant Information ---
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Complainant Details:", 20, 85);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const complainantInfo = [
    `Name: ${complaint.complainant_name || 'N/A'}`,
    `Email: ${complaint.complainant_email || 'N/A'}`,
    `Phone: ${complaint.complainant_phone || 'N/A'}`,
    `Category: ${complaint.category || 'N/A'}`
  ];

  complainantInfo.forEach((info, index) => {
    doc.text(info, 20, 95 + index * 5);
  });

  // --- 4. Complaint Description ---
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Complaint Description:", 20, 125);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const splitText = doc.splitTextToSize(complaint.complaint_text || 'No description provided', 170);
  doc.text(splitText, 20, 135);

  let currentY = 135 + splitText.length * 5;

  // --- 5. Evidence Section ---
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Evidence:", 20, currentY + 10);

  if (complaint.evidence_url) {
    try {
      // Get public URL for evidence
      const { supabase } = await import("../api/supabaseClient");
      const { data } = supabase.storage.from("evidence").getPublicUrl(complaint.evidence_url);
      const evidenceUrl = data.publicUrl;

      // Add evidence image
      doc.addImage(evidenceUrl, 'JPEG', 20, currentY + 20, 80, 60);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text("Evidence attached above", 20, currentY + 85);
      currentY += 90;
    } catch (error) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text("Evidence file available via tracking portal.", 20, currentY + 20);
      currentY += 25;
    }
  } else {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("No evidence provided", 20, currentY + 20);
    currentY += 25;
  }

  // --- 6. Action Required Section ---
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Required Action:", 20, currentY + 10);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Please review and take appropriate action under ${lawSection || 'relevant law'}.`, 20, currentY + 20);

  // --- 7. Signature Section ---
  const sigY = currentY + 35;
  doc.setFontSize(10);
  doc.text("Generated by Lawledge Portal", 20, sigY);
  doc.text("Digital Signature: ____________________", 20, sigY + 10);
  doc.text("Date: ____________________", 120, sigY + 10);

  // --- 8. Footer ---
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("This is an electronically generated official document. For verification, visit: https://lawledgeportal.com", 105, 280, { align: "center" });
  doc.text(`Tracking Verification: https://lawledgeportal.com/track?code=${complaint.tracking_code}`, 105, 285, { align: "center" });

  return doc;
}

export async function saveComplaintPDF(complaint, authority, lawSection) {
  const pdf = await generateComplaintPDF(complaint, authority, lawSection);
  pdf.save(`Complaint_${complaint.tracking_code}.pdf`);
}

// New function to get PDF as blob for email attachment
export async function getComplaintPDFBlob(complaint, authority, lawSection) {
  const pdf = await generateComplaintPDF(complaint, authority, lawSection);
  return pdf.output('blob');
}